# Generated by Django 2.0.6 on 2018-06-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_auto_20180625_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Barang')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Brand')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.KategoriBarang')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Operator')),
            ],
        ),
    ]
