# Generated by Django 2.0.6 on 2018-06-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriBarang',
            fields=[
                ('kategori_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id_operator', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('no_telepon', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
