# Generated by Django 2.0.6 on 2018-06-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('barang_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=50)),
                ('file_barang', models.FileField(upload_to='media')),
                ('harga', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Brand')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.KategoriBarang')),
            ],
        ),
    ]
