# Generated by Django 2.0.6 on 2018-06-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='kode_supplier',
            new_name='supplier_id',
        ),
    ]
