# Generated by Django 2.0.6 on 2018-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20180625_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='file_barang',
            field=models.FileField(upload_to='tema/static/media'),
        ),
    ]
